<a href="https://colab.research.google.com/github/jaeheechillin3/pytorch_projects/blob/main/vid2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import math

In [12]:
# creating tensors
torch.manual_seed(1000)
x1 = torch.empty(2, 3)
print(x1)
print(x1.shape)
x2 = torch.empty_like(x1)
print(x2)
x3 = torch.zeros_like(x1)
print(x3)
x4 = torch.ones_like(x1)
print(x4)
x5 = torch.rand_like(x1)
print(x5)
x6 = x5.to(torch.int32)
print(x6)
x7 = torch.tensor([[1,2,3],[4,5,6]])
print(x7)

# allowed data types: bool, int8, uint8, int 16, int32, int64,
# half, float, double, bfloat

tensor([[2.1715e-18, 2.3081e-12, 2.6302e+20],
        [6.1943e-04, 3.6022e-12, 6.9989e+22]])
torch.Size([2, 3])
tensor([[3.6883e-31, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.8990e+28]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3189, 0.6136, 0.4418],
        [0.2580, 0.2724, 0.6261]])
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# math and logic